language: go

go:
  - 1.7.x
  - 1.8.x
  - master

notifications:
  email:
    on_success: never
    on_failure: always

script:
    go test -coverprofile=cover.out -v
after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=cover.out -service=travis-ci

